input:
  filename: /home/andrea/MyMacros/Correlations_v2/AnalysisResults_MC_3sigma.root
  treename: hf-correlator-d-meson-pairs/
  histoname:
    reconstructed:
      All: hPtVsYMcRec
      Prompt: null
      Nonprompt: null
    generated:
      All: hPtVsYMcGen
      Prompt: null
      Nonprompt: null

pt_bins_limits: [1, 24] # options available: list of bin limits, null to deactivate

rapidity:
  axis: Y # rapidity axis in input histograms, options available: X, Y
  cut: 0.5 # selection |y| < cut on the generated histogram, null if not cut

output:
  dir: ./
  save:
    TEfficiency: True # save TEfficiency instances in output .root file
    TH1: True # save TH1 histograms in output .root file
    TCanvas: # save TCanvas instances in extra files (on top of the standard output .root file)
      individual: True # for individual canvas (All, Prompt, Nonprompt separately)
      overlap: True # for overlap canvas (see overlap entry below)
      extension: pdf, png # root not needed, all canvas are stored in .root file anyway
  plots:
    label: AccEffPreselD0ToKPi_pos0 # label in output files (file names, .root entries)
    y_axis:
      name: "(Acc #times #varepsilon)"
      min: 1.e-3
      max: 1.
      log_scale: True
    overlap: null # options available: All, Prompt, Nonprompt, null (if not overlap wanted)
    watermark: "#color[619]{ALICE Work in progress}" # watermark on top left of the plot's frame
